Repository FarmorAI/farm-web-spring, pull requests merged in 2025-03, with the labels that each got.

#35 Hoon5
  src/main/java/com/farmorai/backend/dto/NoticeDto.java
  src/main/java/com/farmorai/backend/securityFilter/jwt/JwtAuthStrategy.java
  src/main/resources/mappers/NoticeMapper.xml
Labels: enhancement

#36 소셜 로그인 구글/AWS-S3 이미지 업로드
  .gitignore
  build.gradle
  src/main/java/com/farmorai/backend/config/DatabaseConfig.java
  src/main/java/com/farmorai/backend/config/S3Config.java
  src/main/java/com/farmorai/backend/controller/BoardController.java
  src/main/java/com/farmorai/backend/controller/BoardFileController.java
  src/main/java/com/farmorai/backend/controller/MemberController.java
  src/main/java/com/farmorai/backend/controller/NoticeController.java
  src/main/java/com/farmorai/backend/controller/S3Controller.java
  src/main/java/com/farmorai/backend/controller/SocialController.java
  src/main/java/com/farmorai/backend/dto/NoticeDto.java
  src/main/java/com/farmorai/backend/mapper/BoardMapper.java
  src/main/java/com/farmorai/backend/mapper/NoticeMapper.java
  src/main/java/com/farmorai/backend/securityFilter/CustomUserDetails.java
  src/main/java/com/farmorai/backend/securityFilter/MemberDetailsService.java
  src/main/java/com/farmorai/backend/securityFilter/jwt/JwtAuthStrategy.java
  src/main/java/com/farmorai/backend/securityFilter/jwt/JwtFilter.java
  src/main/java/com/farmorai/backend/securityFilter/jwt/JwtTokenProvider.java
  src/main/java/com/farmorai/backend/service/BoardService.java
  src/main/java/com/farmorai/backend/service/MemberService.java
  src/main/java/com/farmorai/backend/service/NoticeService.java
  src/main/java/com/farmorai/backend/service/S3Service.java
  src/main/java/com/farmorai/backend/util/FileUploadUtil.java
  src/main/resources/application.yml
  src/main/resources/application.yml~
  src/main/resources/mappers/NoticeMapper.xml
  src/test/java/com/farmorai/backend/securityFilter/jwt/JwtAuthStrategyTest.java
  src/test/java/com/farmorai/backend/securityFilter/jwt/JwtTokenProviderTest.java
Labels: enhancement, good first issue

#40 Dahye100
  src/main/java/com/farmorai/backend/controller/InfoController.java
  src/main/java/com/farmorai/backend/service/InfoService.java
  src/main/java/com/farmorai/backend/service/WeatherService.java
  upload/c434127e-2a26-4c48-aa41-85c6801901b7_KakaoTalk_20250212_145140758-Photoroom.png
  upload/s_c434127e-2a26-4c48-aa41-85c6801901b7_KakaoTalk_20250212_145140758-Photoroom.png
Labels: enhancement

#41 Songbeom2
  src/main/java/com/farmorai/backend/controller/MemberController.java
  src/main/java/com/farmorai/backend/controller/NoticeController.java
  src/main/java/com/farmorai/backend/controller/ProductController.java
  src/main/java/com/farmorai/backend/dto/MemberDto.java
  src/main/java/com/farmorai/backend/dto/ProductDto.java
  src/main/java/com/farmorai/backend/mapper/MemberMapper.java
  src/main/java/com/farmorai/backend/mapper/ProductMapper.java
  src/main/java/com/farmorai/backend/service/MemberService.java
  src/main/java/com/farmorai/backend/service/ProductService.java
  src/main/java/com/farmorai/backend/service/S3Service.java
  src/main/resources/application.yml
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/NoticeMapper.xml
  src/main/resources/mappers/ProductMapper.xml
Labels: good first issue

#47 Feature/auth update
  src/main/java/com/farmorai/backend/config/MyBatisConfig.java~
  src/main/java/com/farmorai/backend/controller/InquiryController.java
  src/main/java/com/farmorai/backend/dto/MemberRole.java~
  src/main/java/com/farmorai/backend/securityFilter/jwt/JwtFilter.java
  src/main/java/com/farmorai/backend/securityFilter/jwt/JwtTokenProvider.java
  src/main/java/com/farmorai/backend/securityFilter/session/SessionAuthStrategy.java~
  src/main/java/com/farmorai/backend/service/InquiryService.java
Labels: bug, enhancement

#50 Hoon0711
  src/main/java/com/farmorai/backend/controller/MemberController.java
  src/main/java/com/farmorai/backend/dto/response/ApiResponse.java
  src/main/java/com/farmorai/backend/mapper/MemberMapper.java
  src/main/java/com/farmorai/backend/securityFilter/jwt/JwtAuthStrategy.java
  src/main/java/com/farmorai/backend/service/MemberService.java
  src/main/resources/mappers/MemberMapper.xml
Labels: bug

#52 Songbeom00
  src/main/java/com/farmorai/backend/controller/CartController.java
  src/main/java/com/farmorai/backend/controller/NoticeController.java
  src/main/java/com/farmorai/backend/controller/ProductController.java
  src/main/java/com/farmorai/backend/controller/S3Controller.java
  src/main/java/com/farmorai/backend/domain/Cart.java
  src/main/java/com/farmorai/backend/domain/CartItem.java
  src/main/java/com/farmorai/backend/dto/CartItemDto.java
  src/main/java/com/farmorai/backend/dto/CartResponseDto.java
  src/main/java/com/farmorai/backend/dto/response/ApiResponse.java
  src/main/java/com/farmorai/backend/exception/NoticeNotFoundException.java
  src/main/java/com/farmorai/backend/mapper/CartItemMapper.java
  src/main/java/com/farmorai/backend/mapper/CartMapper.java
  src/main/java/com/farmorai/backend/securityFilter/jwt/JwtFilter.java
  src/main/java/com/farmorai/backend/service/CartService.java
  src/main/java/com/farmorai/backend/service/NoticeService.java
  src/main/resources/mappers/CartItemMapper.xml
  src/main/resources/mappers/CartMapper.xml
Labels: good first issue

#53 Songbeom00
  src/main/java/com/farmorai/backend/controller/CartController.java
  src/main/java/com/farmorai/backend/controller/MemberController.java
  src/main/java/com/farmorai/backend/controller/OrderController.java
  src/main/java/com/farmorai/backend/controller/PaymentController.java
  src/main/java/com/farmorai/backend/controller/ProductController.java
  src/main/java/com/farmorai/backend/domain/Order.java
  src/main/java/com/farmorai/backend/dto/OrderDetailDto.java
  src/main/java/com/farmorai/backend/dto/OrderItemDto.java
  src/main/java/com/farmorai/backend/dto/OrderRequestDto.java
  src/main/java/com/farmorai/backend/dto/OrderResponseDto.java
  src/main/java/com/farmorai/backend/dto/OrderStatus.java
  src/main/java/com/farmorai/backend/dto/PaymentPlan.java
  src/main/java/com/farmorai/backend/dto/response/ApiResponse.java
  src/main/java/com/farmorai/backend/mapper/OrderMapper.java
  src/main/java/com/farmorai/backend/securityFilter/jwt/JwtAuthStrategy.java
  src/main/java/com/farmorai/backend/service/FileUploadService.java
  src/main/java/com/farmorai/backend/service/OrderService.java
  src/main/java/com/farmorai/backend/util/OrderUtil.java
  src/main/resources/mappers/OrderMapper.xml
Labels: good first issue

#54 Feature/analysis
  src/main/java/com/farmorai/backend/controller/FileUploadController.java
  src/main/java/com/farmorai/backend/controller/InquiryController.java
  src/main/java/com/farmorai/backend/service/FileUploadService.java
  src/main/java/com/farmorai/backend/util/FileUploadUtil.java
  upload/a6c348a7-38e4-445e-a805-71502d2a1b17_apple_test.jpg
  upload/detected_a6c348a7-38e4-445e-a805-71502d2a1b17_apple_test.jpg
  upload/s_a6c348a7-38e4-445e-a805-71502d2a1b17_apple_test.jpg
Labels: enhancement

#57 Feature/analysis
  src/main/java/com/farmorai/backend/controller/BoardFileController.java
  src/main/java/com/farmorai/backend/controller/FileUploadController.java
  src/main/java/com/farmorai/backend/controller/PaymentController.java
  src/main/java/com/farmorai/backend/dto/AiResultDto.java
  src/main/java/com/farmorai/backend/mapper/AiResultMapper.java
  src/main/java/com/farmorai/backend/mapper/SubsMapper.java
  src/main/java/com/farmorai/backend/service/FileUploadService.java
  src/main/java/com/farmorai/backend/service/SubsService.java
  src/main/resources/mappers/AiResultMapper.xml
  src/main/resources/mappers/SubsMapper.xml
Labels: enhancement

#58 Songbeom00
  build.gradle
  docker-compose.yaml
  logstash/lib/mysql-connector-j-9.2.0.jar
  logstash/pipeline/logstash.conf
  src/main/java/com/farmorai/backend/BackendApplication.java
  src/main/java/com/farmorai/backend/controller/CartController.java
  src/main/java/com/farmorai/backend/controller/MemberController.java
  src/main/java/com/farmorai/backend/controller/NoticeController.java
  src/main/java/com/farmorai/backend/controller/OrderController.java
  src/main/java/com/farmorai/backend/controller/PaymentController.java
  src/main/java/com/farmorai/backend/controller/ProductController.java
  src/main/java/com/farmorai/backend/domain/ProductDoc.java
  src/main/java/com/farmorai/backend/dto/NoticeDto.java
  src/main/java/com/farmorai/backend/dto/response/ApiResponse.java
  src/main/java/com/farmorai/backend/global/response/ResponseApi.java
  src/main/java/com/farmorai/backend/global/response/ResponseAspect.java
  src/main/java/com/farmorai/backend/mapper/NoticeMapper.java
  src/main/java/com/farmorai/backend/repository/NoticeDocRepository.java
  src/main/java/com/farmorai/backend/securityFilter/jwt/JwtAuthStrategy.java
  src/main/java/com/farmorai/backend/service/NoticeService.java
  src/main/resources/application.yml
  src/main/resources/elasticsearch/mappings.json
  src/main/resources/elasticsearch/settings.json
  src/main/resources/mappers/NoticeMapper.xml
  src/test/java/com/farmorai/backend/mapper/MemberMapperTest.java
  src/test/java/com/farmorai/backend/mapper/NoticeMapperTest.java
  src/test/resources/application.yml
Labels: enhancement

#59 CartPayment process update
  docker.md
  logstash/pipeline/logstash.conf
  src/main/java/com/farmorai/backend/controller/OrderController.java
  src/main/java/com/farmorai/backend/controller/PaymentController.java
  src/main/java/com/farmorai/backend/controller/ProductController.java
  src/main/java/com/farmorai/backend/dto/PaymentPlan.java
  src/main/java/com/farmorai/backend/mapper/CartMapper.java
  src/main/java/com/farmorai/backend/mapper/PaymentMapper.java
  src/main/java/com/farmorai/backend/mapper/ProductMapper.java
  src/main/java/com/farmorai/backend/repository/ProductDocRepository.java
  src/main/java/com/farmorai/backend/service/NoticeService.java
  src/main/java/com/farmorai/backend/service/OrderService.java
  src/main/java/com/farmorai/backend/service/PaymentService.java
  src/main/java/com/farmorai/backend/service/ProductService.java
  src/main/resources/elasticsearch/mappings.json
  src/main/resources/mappers/CartMapper.xml
  src/main/resources/mappers/NoticeMapper.xml
  src/main/resources/mappers/PaymentMapper.xml
  src/main/resources/mappers/ProductMapper.xml
Labels: good first issue

#64 Songbeom00
  build.gradle
  src/main/java/com/farmorai/backend/config/RedisConfig.java
  src/main/java/com/farmorai/backend/controller/NoticeController.java
  src/main/java/com/farmorai/backend/controller/ProductController.java
  src/main/java/com/farmorai/backend/domain/ProductDoc.java
  src/main/java/com/farmorai/backend/dto/NoticeDto.java
  src/main/java/com/farmorai/backend/dto/PageRequestDto.java
  src/main/java/com/farmorai/backend/dto/PageResponseDto.java
  src/main/java/com/farmorai/backend/dto/ProductDto.java
  src/main/java/com/farmorai/backend/mapper/ProductMapper.java
  src/main/java/com/farmorai/backend/repository/ProductDocRepository.java
  src/main/java/com/farmorai/backend/service/NoticeService.java
  src/main/java/com/farmorai/backend/service/ProductService.java
  src/main/resources/application.yml
  src/main/resources/mappers/ProductMapper.xml
  src/test/java/com/farmorai/backend/mapper/NoticeMapperTest.java
  src/test/java/com/farmorai/backend/mapper/ProductMapperTest.java
  src/test/java/com/farmorai/backend/service/NoticeServiceTest.java
  src/test/java/com/farmorai/backend/service/ProductServiceTest.java
  src/test/resources/application.yml
Labels: enhancement, good first issue
